import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import SidebarLayout from "@/components/SidebarLayout";
import { AUTH_COOKIE_NAME, verifyAuthToken } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get(AUTH_COOKIE_NAME)?.value;
  let roles: string[] = [];
  let username: string | undefined;

  if (token) {
    const payload = await verifyAuthToken(token);
    if (payload) {
      roles = payload.roles;
      username = payload.username;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarLayout roles={roles} username={username}>
          {children}
        </SidebarLayout>
      </body>
    </html>
  );
}
